### ISSUE TITLE
v2.6.0 is missing a Linux release

### ISSUE THREAD

**Issue by xathon** [Yamato-Security/takajo#180]
Like the title says, it seems the Linux release has been removed for some reason. It would be great if you could restore it. I can build it myself in the meantime, but still, having the binary available would help.

**Comment by YamatoSecurity** [comment]
@xathon Did the GNU version of the linux binary work for you?
We currently cannot compile static linux binaries due to this issue: https://github.com/Yamato-Security/takajo/issues/160
Since there is a large chance that people won't be able to use the GNU version unless they have the same linux environment, we are currently not creating the linux binaries. Although I suppose if people are able to use them then we could.

**Comment by YamatoSecurity** [comment]
@xathon We improved our binary release process and started creating linux binaries again. You can get it here: https://github.com/Yamato-Security/takajo/releases/tag/v2.6.0
