### ISSUE TITLE
Remove unused `pcre64.dll` from Windows release package

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/takajo#62]
**Describe the issue**
Remove unused `pcre64.dll` from Windows release binary.
When I checked, all Takajo command errors did not occur for the results of hayabusa-sample-evtx on Window 11.

**Environment**
 - OS: Windows11
 - Takajo version: 2.1.0

@YamatoSecurity 
It seems possible to remove `pcre64.dll`, but Was there any reason to include pcre64.dll in the release package?🤔

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks for checking this! Ideally I want to compile everything statically and not require extra dlls but when I tried this on Windows 10 I got an error about not having `pcre64.dll` so that is why I included it. That is weird that it works without it on Windows 11. I will test it out on a couple of more environments to see if it is needed or not.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Sorry...🙇‍♀️  In my environment, pcre64.dll was in the PATH, so it didn't seem to cause an error. I'll close this issue!
